[project]
name = "my-agent"
version = "0.0.1"
description = "my-agent"
authors = [{ name = "John Doe", email = "john.doe@myemail.com" }]
dependencies = [
    "uipath-langchain>=0.0.106",
    "langchain-anthropic>=0.3.8",
]
requires-python = ">=3.10"
